version: "3"

services:
  web:
    container_name: django-todo-api
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"

  frontend:
    container_name: react-todo-front
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      back-tier:
    stdin_open: true
    tty: true


networks:
  back-tier:
    driver: bridge